[package]
name = "lucky-draw-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sails-rs = "0.8.1"
scale-info = { version = "*", default-features = false }
parity-scale-codec = { version = "*", default-features = false }
