[package]
name = "lucky_draw_app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd.workspace = true
sails-rs.workspace = true
scale-info = { version = "*", default-features = false }
parity-scale-codec = { version = "*", default-features = false }
