constructor {
  New : (name: str);
};

service Token {
  Mint : (to: actor_id, amount: u256) -> null;
  Transfer : (from: actor_id, to: actor_id, amount: u256) -> null;
  query BalanceOf : (account: actor_id) -> u256;
  query Name : () -> str;

  events {
    Transfer: struct { from: actor_id, to: actor_id, amount: u256 };
  }
};

