[package]
name = "counter-with-event-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs = "0.9.0"
scale-info = { version = "*", default-features = false }
parity-scale-codec = { version = "*", default-features = false }
