constructor {
  New : (counter: actor_id);
};

service CounterProxy {
  Inc : () -> i32;
  IncRemoting : () -> i32;
  query Counter : () -> actor_id;
  query Get : () -> i32;
  query GetRemoting : () -> i32;

  events {
    Incremented: i32;
  }
};

