[package]
name = "counter-event-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = "0.6.1"
scale-info = { version = "*", default-features = false }
parity-scale-codec = { version = "*", default-features = false }