name: counter-with-event
basedir: ../target/wasm32-gear
basename: counter_with_event
build:
  release:
    code_id: "0x5890d1dfac9b46a3aa498474f57760cc419664569c1967e3e82b4507a8ce50a1"
  debug:
    code_id: "0xbbfbf45097627685bed067c31667bd3757a47eaf034f539d88ed2186844dab51"
deploy:
  idl: |+
    constructor {
      /// set initial value
      New : (initial_value: i32);
    };

    service Counter {
      /// increment counter by 1
      Inc : () -> i32;
      /// get counter value
      query Get : () -> i32;

      events {
        /// counter incremented to value
        IncrementedTo: i32;
      }
    };

  args:
    - 42
  code_id: "0x5890d1dfac9b46a3aa498474f57760cc419664569c1967e3e82b4507a8ce50a1"
  program_id: "0xfc9c62661d6af691f53872f9b485f457315844eeb93ff0f6a54bfcc3694edd46"
  rpc: wss://testnet.vara.network
